name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build, Test & Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore health-check.slnx

      - name: Build
        run: dotnet build health-check.slnx --no-restore -c Release

      - name: Test
        run: dotnet test health-check.slnx --no-build -c Release --logger "trx;LogFileName=test-results.trx"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: "**/test-results.trx"

      - name: Build Docker image
        run: docker build -t orders-api:${{ github.sha }} .
